// Authentication
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_BY_PHONE = 'SIGN_IN_BY_PHONE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';
export const CHECK_EXISTING_EMAIL_PHONE = 'CHECK_EXISTING_EMAIL_PHONE';
export const EMAIL_PHONE_EXISTED = 'EMAIL_PHONE_EXISTED';
export const EMAIL_PHONE_NOT_EXISTED = 'EMAIL_PHONE_NOT_EXISTED';
export const ACCOUNT_REGISTRATION = 'ACCOUNT_REGISTRATION';
export const EMAIL_VERIFICATION_SENDING = 'EMAIL_VERIFICATION_SENDING';
export const EMAIL_VERIFICATION_DONE = 'EMAIL_VERIFICATION_DONE';
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SKIP_UPDATE_PROFILE = 'SKIP_UPDATE_PROFILE';

// Screen Navigation
export const ACCOUNT_TAB = 'ACCOUNT_TAB';
export const HOME_TAB = 'HOME_TAB';
export const BROWSE_TAB = 'BROWSE_TAB';
export const NOTIFICATION_TAB = 'NOTIFICATION_TAB';
export const CART_TAB = 'CART_TAB';

// Password reset & change
export const RESET_PASSWORD = 'RESET_PASSWORD';

// clear alert message
export const DISPLAY_ALERT_MESSAGE = 'DISPLAY_ALERT_MESSAGE';
export const CLEAR_ALERT_MESSAGE = 'CLEAR_ALERT_MESSAGE';

// add to cart
export const RETRIEVE_CART = 'RETRIEVE_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const CART_IS_EMPTY = 'CART_IS_EMPTY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_CART = 'UPDATE_CART';
export const SAVE_TO_HISTORY_CART = 'SAVE_TO_HISTORY_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const RE_ORDER = 'RE_ORDER';
export const PLACED_ORDER = 'PLACED_ORDER';

// order status
export const ORDER_CONFIRMED = 'ORDER_CONFIRMED';
export const ORDER_COMPLETED = 'ORDER_COMPLETED';

// set location
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const AUTO_SET_LOCATION = 'AUTO_SET_LOCATION';

// socket
export const SOCKET_CONNECTION = 'SOCKET_CONNECTION';
export const SOCKET_DISCONNECTION = 'SOCKET_DISCONNECTION';
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
export const CHECKED_NOTIFICATION = 'CHECKED_NOTIFICATION';
