// Authentication
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_BY_PHONE = 'SIGN_IN_BY_PHONE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';
export const ACCOUNT_REGISTRATION = 'ACCOUNT_REGISTRATION';
export const EMAIL_VERIFICATION_SENDING = 'EMAIL_VERIFICATION_SENDING';
export const EMAIL_VERIFICATION_DONE = 'EMAIL_VERIFICATION_DONE';
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SKIP_UPDATE_PROFILE = 'SKIP_UPDATE_PROFILE';

// Screen Navigation
export const ACCOUNT_TAB = 'ACCOUNT_TAB';
export const HOME_TAB = 'HOME_TAB';
export const BROWSE_TAB = 'BROWSE_TAB';
export const NOTIFICATION_TAB = 'NOTIFICATION_TAB';
export const CART_TAB = 'CART_TAB';

// Password reset & change
export const RESET_PASSWORD = 'RESET_PASSWORD';
